---
title: "Updated codebook"
author: "Data Drama Queens"
date: "2025-09-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

In this document we have included updates to variable names, transformations, and deletions in the dataset [20250905-tidy-exam-data.txt](data/data-for-analysis/20250905-tidy-exam-data.txt). Each variable entry includes its definition, and changes from the previous version.


## Changed and Added Columns: 

```{r, echo=FALSE}
Changed_data <- tribble(
  ~Var., ~Description, ~Changes,
  "neut_percent", "Percent of Neutrophils in WBC count", "Renamed from %neut",
  "lymph_percent", "Percent of Lymphocytes in WBC count", "Renamed from lymph%",
  "age_days", "Days of life", "Renamed from days of life",
  "sodium", "Sodium", "Renamed from sod",
  "potassium", "Potassium", "Renamed from pot",
  "chloride", "Chloride", "Renamed from chlor",
  "bicarbonate", "Bicarbonate", "Renamed from co2",
  "blood_urea_nitrogen", "Blood Urea Nitrogen", "Renamed from un",
  "mcv", "Mean Corpuscular (RBC) Volume", "Pivotted from mean_RBC_characteristic and mean_value",
  "mch", "Mean Corpuscular (RBC) Hemoglobin", "Pivotted from mean_RBC_characteristic and mean_value",
  "mchc", "Mean Corpuscular (RBC) Hemoglobin per Cell", "Pivotted from mean_RBC_characteristic and mean_value",
  "hgb_quartiles", "Hemoglobin quartiles", "Cut the Hemoglobin level into quartiles",
  "blood_ure_nitrogen_over_30", "blood urea nitrogen above 30", "Create a column indicating if the blood urea nitrogen is above 30",
  "lymph_count", "Lymphocytes cell count", "Create a column for Lymphocytes cell count",
  "sodium_fraction", "Sodium as a fraction of summed sodium, potassium, and chloride", "Create a column for sodium fraction ",
  "age_years", "Age in years", "New variable created from age_days variable"
)

knitr::kable(Changed_data)
```
---



## Deleted Columns and Justifications:

```{r, echo=FALSE}
deleted_data <- tribble(
  ~Var., ~Description, ~Changes,
  "wbc_copy", "An identcal copy of wbc column", "Removed duplicated column",
  "hct", "Hematocrit", "Removed unnecessary columns",
  "rdw", "Red cell Distribution Width", "Removed unnecessary columns",
  "mean_RBC_characteristic", "one of: mcv = Mean Corpuscular (RBC) Volume; mch = Mean Corpuscular (RBC) Hemoglobin; mchc = Mean Corpuscular (RBC) Hemoglobin per Cell", "Removed after pivoting", "mean_value", "	value for each of mean_RBD_characteristic", "Removed after pivoting"
)

knitr::kable(deleted_data)
```


